# Generated by Django 3.2 on 2021-04-26 16:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255, unique=True)),
                ('event_date', models.DateField()),
                ('event_location', models.CharField(max_length=255)),
                ('initial_tickets', models.PositiveIntegerField(blank=True)),
                ('event_status', models.CharField(choices=[('OnTime', 'OnTime'), ('Rescheduled', 'Rescheduled'), ('Cancelled', 'Cancelled')], default='OnTime', max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.CharField(editable=False, max_length=8, primary_key=True, serialize=False)),
                ('no_of_tickets', models.PositiveIntegerField(blank=True, null=True)),
                ('redeemed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='core.event')),
            ],
        ),
    ]
